### ISSUE TITLE
Traduction des boutons admin

### ISSUE THREAD

**Issue by will94290** [OpenSourcePolitics/decidim-efb#10]
Ludivine,
Dans le fichier `decidim-efb/decidim-polis/app/views/.../show.html.erb` j'ai fait des traductions qui sont dans `config/polis.yml`.
Mais il y a une chose que je n'arrive pas à traduire ce sont tes boutons qui sont dans le script javascript.
Donc si tu pouvais faire en sorte qu'ils chopent les traductions de le même fichier que moi ce serait cool.
💯 😄  Merci d'avance ^^

**Comment by virgile-dev** [comment]
@ludivinecp est-ce que c'est galère de rajouter une trad en néerlandais de ces boutons ?

**Comment by juliesimon** [comment]
Up !
@moustachu, on doit traduire les boutons Commentaires, Participants, Statistiques, Synthèse qui sont dans cette fonction du script dans `decidim-efb/decidim-polis/app/views/.../show.html.erb`
Avant de passer des heures à voir si je peux résoudre ça toute seule, tu as une idée ?

```
function completeUrl(conversation_id){
  $(".appendModerateLink").append("<li><a class= 'btn admin-btn' target= 'blank' href= 'https://pol.is/m/"+ conversation_id + "/comments'> Commentaires </a> </li>")
  $(".appendModerateLink").append("<li><a class= 'btn admin-btn' target= 'blank' href= 'https://pol.is/m/"+ conversation_id + "/participants'> Participants </a></li>")
  $(".appendAdminLink").append("<li><a class= 'btn admin-btn' target= 'blank' href= 'https://pol.is/m/"+ conversation_id + "/stats'> Statistiques </a> </li>")
  $(".appendAdminLink").append("<li><a class= 'btn admin-btn' target= 'blank' href= 'https://pol.is/m/"+ conversation_id + "/export'> Export </a> </li>")
  $(".appendAdminLink").append("<li><a class= 'btn admin-btn' target= 'blank' href= 'https://pol.is/m/"+ conversation_id + "/reports'> Synthèse </a> </li>")
  }
```

**Comment by ludivinecp** [comment]
@juliesimon je pense que tu es obligée de passer par une gem pour faire ça. Javascript ne gère pas la traduction de rails.
Regarde de ce côté là  ça pourra surement t'aider : https://github.com/fnando/i18n-js

**Comment by moustachu** [comment]
à priori c'est bon pour le plan traduction. 
Il y avait surtout du taff sur le fichier `decidim-polis/app/views/decidim/polis/polis/show.html.erb` et d'architecture.

On peut esquiver le plan i18n / Rails / JS vu que pour l'instant c'est du script généré avec la vue. 

Par contre j'ai fait sauté le switch dans le `polis.yml` qui permettait de changer de **site_id** par orga. Il faudra le remettre mais en tant que paramètre dans `/system` ou `/admin` si on veut retrouver quelque chose de cohérent et pérenne.
