### ISSUE TITLE
Bug with multilingual navigation in participatory processes

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-efb#15]
When I select french in the nav bar and then try to navigate to another feature in the participatory process the page keeps switching to NL. See gif bellow to observe the bug.
![multi-languagebug](https://user-images.githubusercontent.com/11473995/35970853-2676c364-0ccc-11e8-8c41-c3d0378f23c4.gif)

I was able to reproduce the bug only on haddock with the NL and FR languages activated. On tintin the language transition works OK.

**Comment by virgile-dev** [comment]
A little update on this one. I noticed that if I changes de default locale of the organisation (in admin panel > config) the bug is inverted. When I select NL as language, when I navigate in participatory process it switches back to french.

**Comment by virgile-dev** [comment]
A little update on this one. I noticed that if I changes de default locale of the organisation (in admin panel > config) the bug is inverted. When I select NL as language, when I navigate in participatory process it switches back to french.

**Comment by virgile-dev** [comment]
I also checked on staging.decidim.codegram.com I was not able to reproduce the bug.

**Comment by juliesimon** [comment]
@virgile-dev je n'ai pas ce problème en local, je vais tester en déploiement sur heroku mais j'espère que le passage à la 0.9-stable a résolu le problème
EDIT : je n'ai pas le bug non plus sur https://bosa.opensourcepolitics.eu/ (redirection depuis haddock)

![videoscreenshot_bosa](https://user-images.githubusercontent.com/29771726/36390859-ba120332-15a4-11e8-9ed0-984b7cf5e522.gif)
