### ISSUE TITLE
Error messages in English

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-efb#16]
On haddock only NL and FR are activated, though users are getting error messages in English. 
<img width="1093" alt="capture d ecran 2018-02-08 a 12 23 28" src="https://user-images.githubusercontent.com/11473995/35971239-94130814-0ccd-11e8-8bf5-2189e7babf80.png">
<img width="1087" alt="capture d ecran 2018-02-08 a 12 23 12" src="https://user-images.githubusercontent.com/11473995/35971200-694ad4c2-0ccd-11e8-8a1e-37accd8dbb1c.png">

**Comment by juliesimon** [comment]
@virgile-dev ça semble résolu
<img width="989" alt="capture d ecran 2018-02-19 a 19 17 01" src="https://user-images.githubusercontent.com/29771726/36392024-813a4baa-15a9-11e8-9f55-03badbd5493b.png">
