### ISSUE TITLE
Isolate the Pol.is feature in an engine

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-efb#19]
This task has been started by @juliesimon on this repo : https://github.com/OpenSourcePolitics/decidim-polis

- [ ] the config file pairing organization name with polis_site_id is inside the main app, we need to locate it in the engine (see https://github.com/OpenSourcePolitics/decidim-polis/issues/1)

Optimization : 
- [ ] Pairing `orginization name` with `polis_site_id` **is really not ideal as the admin can change the org name in the admin panel and then the Pol.is conversations don't show anymore**. It has happenned to me. Would be best if can be paired with something more unique the admin can't change : organization host, org unique id or something like that

**Comment by juliesimon** [comment]
@virgile-dev quelle deadline ? pas de dev dispo cette semaine

**Comment by virgile-dev** [comment]
Semaine prochaine
